Update gradle-publish.yml

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -32,11 +32,23 @@ jobs:
     - name: Print current directory
       run: pwd
 
+    - name: Verify gradlew file
+      run: |
+        if [ ! -f ./gradlew ]; then
+          echo "gradlew file not found"
+          exit 1
+        else
+          echo "gradlew file found"
+        fi
+
     - name: Grant execute permission for gradlew
       run: chmod +x ./gradlew
 
     - name: List directory contents after chmod
       run: ls -la
+
+    - name: Verify gradlew permissions
+      run: ls -la ./gradlew
 
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
